#!/usr/bin/env bash

fin project rm -f
fin project start

# Install composer dependencies
fin composer install

# Make sure the Symfony frontend gets built.
fin exec npm install
fin exec npm run build

fin symfony-init